<a href="https://colab.research.google.com/github/tleitchColumbia/week5/blob/main/Numpy_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,4)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b = 1

In [ ]:
a + b

array([2, 3, 4])

In [ ]:
c = np.arange(2,5)

In [ ]:
(a,c)

(array([1, 2, 3]), array([2, 3, 4]))

In [ ]:
a+c+1

array([4, 6, 8])