<a href="https://colab.research.google.com/github/tleitchColumbia/week5/blob/main/Numpy_Indexing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
nums = np.arange(1,11)*100

idx = np.arange(10)

print(idx)

print(nums[idx])

idx_rand = idx.copy()
np.random.shuffle(idx_rand)

nums[idx_rand]



[0 1 2 3 4 5 6 7 8 9]
[ 100  200  300  400  500  600  700  800  900 1000]


array([ 200,  100,  400,  800,  500,  900,  700, 1000,  600,  300])

In [ ]:
mat = np.arange(1,13).reshape(3,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mat[:,0]

array([1, 5, 9])

In [ ]:
mat[0,:]

array([1, 2, 3, 4])

In [ ]:
mat[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
mat[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mat[-1,-2]

11

In [ ]:
# Mask

In [ ]:
mask = mat[:,3] >7

In [ ]:
mat[mask]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mask

array([False,  True,  True])