<a href="https://colab.research.google.com/github/tleitchColumbia/week5/blob/main/Numpy_Indexing_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
nums = np.arange(1,11)*100

In [ ]:
nums

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
nums[:5]

array([100, 200, 300, 400, 500])

In [ ]:
nums[5:]

array([ 600,  700,  800,  900, 1000])

In [ ]:
nums[0]

100

In [ ]:
nums[1]

200

In [ ]:
nums[-1]

1000

In [ ]:
nums[-2]

900

In [ ]:
nums[-3:]

array([ 800,  900, 1000])

In [ ]:
nums[2:5]

array([300, 400, 500])